import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import client from "@/lib/apollo-client";
import {GraphQlApolloProvider} from "@/context/GraphQlApolloProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SessionAuthProvider>
            <html lang="en">
            <body className={inter.className}>
            <GraphQlApolloProvider>
                {children}
            </GraphQlApolloProvider>
            </body>
            </html>
        </SessionAuthProvider>

    );
}
