@url ="https://c19-137-m-node-react-backend.onrender.com"

##Authentication


### Login

GRAPHQL {{url}}/graphql

mutation SignIn($email: String!, $password: String!) {
    signIn(email: $email, password: $password) {
        code
        message
        success
        token
        expire_at
    }
}


{
  "email": "yeimar112003@gmail.com",
  "password": "12345678"
}


### Registro
GRAPHQL {{url}}/graphql

mutation SignUp($data: CreateUserInput!) {
    signUp(data: $data) {
        code
        success
        message
        token
    }
}

{
  "data": {
    "email": "orlandocardenas0107@gmail.com",
    "first_name": "Orlando",
    "last_name": "Cardenas",
    "nickname": "orlando",
    "password": "12345678",
    "password_confirmation": "12345678"
  }
}

### Olvide mi contraseña
GRAPHQL {{url}}/graphql

mutation ForgotPassword($email: String!) {
    forgotPassword(email: $email) {
        code
        success
        message
    }
}

{
  "email": "yeimar112003@gmail.com"
}

### Cambiar contraseña
GRAPHQL {{url}}/graphql

mutation ResetPassword($data: ResetPasswordInput!) {
    resetPassword(data: $data) {
        code,
        message,
        success
    }
}

  {
  "data": {
    "confirmNewPassword": "123456",
    "newPassword": "123456",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InllaW1hcjExMjAwM0BnbWFpbC5jb20iLCJzdWIiOiI3ZmUwYzg0MS1hMzQ0LTQxYzYtYjI3Yi04OTMzMTk2Mjk1ZGQiLCJpYXQiOjE3MjA5OTA4NjQsImV4cCI6MTcyMDk5NDQ2NH0.YTgw8I8Q8_Eldv8lqE_lzH5j-rHnaKwOHuQ4_8Ff81s"
  }
}


